//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFK5517
    {
        public string K5517_IRCode { get; set; }
        public string K5517_DateCreate { get; set; }
        public string K5517_DateEdit { get; set; }
        public string K5517_DateReceiveExpect { get; set; }
        public string K5517_Creator { get; set; }
        public string K5517_Editor { get; set; }
        public string K5517_Beneficiary { get; set; }
        public string K5517_Agent { get; set; }
        public string K5517_CommercialTerm { get; set; }
        public string K5517_PaymentCondition { get; set; }
        public string K5517_Currency { get; set; }
        public string K5517_DateExchange { get; set; }
        public Nullable<decimal> K5517_ExchangeRate { get; set; }
        public string K5517_VAT { get; set; }
        public string K5517_Market { get; set; }
        public string K5517_InboundKind { get; set; }
        public string K5517_Warehouse { get; set; }
        public string K5517_Remark { get; set; }
        public string K5517_ContractCode { get; set; }
        public string K5517_ContractNo { get; set; }
        public string K5517_InboundNo { get; set; }
        public string K5517_InvoiceNo { get; set; }
        public string K5517_InvoiceDate { get; set; }
        public string K5517_InvoiceCode { get; set; }
        public string K5517_InvoiceForm { get; set; }
        public string K5517_DeclarationNo { get; set; }
        public string K5517_DeclarationDate { get; set; }
        public string K5517_Package { get; set; }
        public string K5517_GrossWeight { get; set; }
        public Nullable<decimal> K5517_AdditionalCost { get; set; }
        public Nullable<decimal> K5517_HandlingFee { get; set; }
        public Nullable<decimal> K5517_ImpTax { get; set; }
        public Nullable<decimal> K5517_SpeConTax { get; set; }
        public Nullable<decimal> K5517_EnvTax { get; set; }
        public Nullable<decimal> K5517_ImpVAT { get; set; }
        public Nullable<decimal> K5517_DocumentationFee { get; set; }
        public Nullable<decimal> K5517_TerminalHandlingFee { get; set; }
        public string K5517_CurrencyAdditionalCost { get; set; }
        public string K5517_CurrencyHandlingFee { get; set; }
        public string K5517_CurrencyImpTax { get; set; }
        public string K5517_CurrencySpeConTax { get; set; }
        public string K5517_CurrencyEnvTax { get; set; }
        public string K5517_DateComplete { get; set; }
        public string K5517_DateApproval { get; set; }
        public string K5517_DateCancel { get; set; }
        public string K5517_CheckState { get; set; }
        public string K5517_BOL { get; set; }
        public string K5517_BOLDate { get; set; }
        public string K5517_InvoiceLink { get; set; }
    }
}
