//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFK5518
    {
        public string K5518_IRCode { get; set; }
        public decimal K5518_IRSeq { get; set; }
        public string K5518_POCode { get; set; }
        public Nullable<decimal> K5518_POSeq { get; set; }
        public string K5518_FILENO { get; set; }
        public string K5518_MODEL { get; set; }
        public string K5518_CBNO { get; set; }
        public string K5518_SZNO { get; set; }
        public string K5518_ASRTYPE { get; set; }
        public string K5518_ASRCODE { get; set; }
        public string K5518_ASRCBNO { get; set; }
        public string K5518_ASRSZNO { get; set; }
        public Nullable<decimal> K5518_QtyBooking { get; set; }
        public Nullable<decimal> K5518_QtyRequestIn { get; set; }
        public Nullable<decimal> K5518_Tolerance { get; set; }
        public Nullable<decimal> K5518_Price { get; set; }
        public string K5518_Supplier { get; set; }
        public string K5518_DateReceiveExpect { get; set; }
        public string K5518_DateComplete { get; set; }
        public string K5518_DateApproval { get; set; }
        public string K5518_DateCancel { get; set; }
        public string K5518_CheckState { get; set; }
        public string K5518_Remark { get; set; }
        public string K5518_PRCode { get; set; }
        public Nullable<decimal> K5518_PRSeq { get; set; }
        public string K5518_Remark_V2 { get; set; }
    }
}
