//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT_PLM_TC
    {
        public long RHE_ID { get; set; }
        public string RHE_NUMBER { get; set; }
        public string REF_DOC_NUMBER { get; set; }
        public Nullable<System.DateTime> RECEIPT_DATE { get; set; }
        public string RV_MEANING { get; set; }
        public string NAME { get; set; }
        public string IIT_CODE { get; set; }
        public string TEN_VT { get; set; }
        public string UOM_CODE { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public Nullable<decimal> ACTUAL_QUANTITY { get; set; }
        public string IAT_CODE2 { get; set; }
        public string IAT_CODE9 { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE11 { get; set; }
        public string CONTRACT_NUMBER2 { get; set; }
        public string CUSTOMS_DECLARATION_NUMBER { get; set; }
        public Nullable<System.DateTime> CUSTOMS_DECLARATION_DATE { get; set; }
        public string BILL_NUMBER { get; set; }
        public Nullable<System.DateTime> BILL_DATE { get; set; }
        public string STO_CODE { get; set; }
        public string ATTRIBUTE7 { get; set; }
    }
}
