//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STORE
    {
        public string STO_CODE { get; set; }
        public string CLASS { get; set; }
        public string TYPE { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string CCE_ID { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string PROVINCE { get; set; }
        public string COUNTRY { get; set; }
        public string TELEPHONE { get; set; }
        public string FAX { get; set; }
        public string STOREKEEPER { get; set; }
        public string REAL { get; set; }
        public string STATUS { get; set; }
        public System.DateTime EFFECTIVE_DATE_FROM { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_DATE_TO { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string ACO_ID { get; set; }
        public string RD_CONTROL { get; set; }
        public Nullable<long> OUN_ID { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
        public string ATTRIBUTE6 { get; set; }
        public string ATTRIBUTE7 { get; set; }
        public string ATTRIBUTE8 { get; set; }
        public string ATTRIBUTE9 { get; set; }
        public string ATTRIBUTE10 { get; set; }
        public string STO_NUMBER { get; set; }
        public string SAR_ITEM_CONTROL { get; set; }
    }
}
